name: Merge main
on:
  push:
    branches:
      - main-1

jobs:
  deploy:
    name: Setup and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: "275.0.0"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Set up gcloud prod
        run: |
          gcloud config set project ${{ secrets.PROJECT }}
      - name: Docker login
        run: |
          gcloud auth configure-docker
      - name: Build
        run: |-
          docker build \
            --tag gcr.io/${{ secrets.PROJECT }}/${{ secrets.GCP_IMAGE }}:develop \
            .
      - name: Publish
        run: |-
          docker push gcr.io/${{ secrets.PROJECT }}/${{ secrets.GCP_IMAGE }}:develop
